language: node_js
node_js:
  - '18'
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t asheshlal/docker-react .

script:
  - docker run asheshlal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker-frontend'
  env: 'docker-frontend-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-311924022258'
  bucket_path: 'docker-frontend'
  on:
    branch: main
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: '${AWS_SECRET_KEY}'
